name: Turtle Tests

on:
  schedule:
    - cron: '0 2 * * 6' # Every Saturday at 2am UTC

jobs:
  test:
    concurrency:
      group: turtle-${{ matrix.example }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [cloudbalancing, conferencescheduling, curriculumcourse, examination, flightcrewscheduling, machinereassignment, meetingscheduling, nurserostering, pas, projectjobscheduling, taskassigning, tennis, travelingtournament, tsp, vehiclerouting]
    steps:
      - name: Setup Temurin 21 and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Clone timefold-solver
      - name: Checkout timefold-solver
        uses: actions/checkout@v4
        with:
          repository: TimefoldAI/timefold-solver
          path: ./timefold-solver
      - name: Quickly build timefold-solver
        working-directory: ./timefold-solver
        shell: bash
        run: mvn -B -Dquickly clean install

      # Clone timefold-solver-enterprise
      - name: Checkout timefold-solver-enterprise
        uses: actions/checkout@v4
        with:
          repository: TimefoldAI/timefold-solver-enterprise
          token: ${{ secrets.JRELEASER_GITHUB_TOKEN }} # Safe; only used to clone the repo and not stored in the fork.
          path: ./timefold-solver-enterprise
      - name: Quickly build timefold-solver-enterprise
        working-directory: ./timefold-solver-enterprise
        shell: bash
        run: mvn -B -Dquickly clean install

      # Clone timefold-solver-benchmarks
      - name: Checkout timefold-solver-benchmarks
        uses: actions/checkout@v4
        with:
          repository: TimefoldAI/timefold-solver-benchmarks
          path: ./timefold-solver-benchmarks
      - name: Build and test timefold-solver-benchmarks
        working-directory: ./timefold-solver-benchmarks
        shell: bash
        run: mvn clean install -DskipTests

      - name: Run the test per example
        working-directory: ./timefold-solver-benchmarks/examples
        run: mvn -B -Dai.timefold.solver.benchmarks.examples.turtle=${{matrix.example}} -Dai.timefold.solver.benchmarks.examples.turtle.runTimeLimitMinutes=300 test